package com.example.feature_daily_weather_details.ui.adapter_delegates

import com.example.core.ui.DisplayableItem
import com.example.feature_daily_weather_details.databinding.DailyWeatherRecyclerItemBinding
import com.example.feature_daily_weather_details.domain.models.WeatherForTimeOfDayDisplayableItem
import com.hannesdorfmann.adapterdelegates4.dsl.adapterDelegateViewBinding

